### ISSUE TITLE
tag ordering

### ISSUE THREAD

**Issue by nelg** [int128/terraform-aws-nat-instance#16]
we've had a case where plans show up as changes  in the  resource "aws_autoscaling_group" "this"
resource, because the "name" tag in AWS, is like the 4th tag down, and in this module, the name tag is at the bottom.  It then tries to update the tags, but has no effect.

I suggest using the for_each loop, instead of in the local in the variables.tf, to use it in the autoscaling group, and add multiple tag blocks , rather than a single tags attribute containing the array of tags.

**Comment by int128** [comment]
Thank you for contribution!
